config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'products#index'

  resources :carts, only: %i[show destroy], path: 'my_cart'
  resource :cart, only: :show, as: :my_cart, path: 'my_cart'
  resources :products do
    resources :line_items, only: %i[create new create destroy]
  end

  resources :line_items
  post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'

  resources :orders, only: %i[index show new]
  resources :charges, only: %i[new create]

  resources :categories, only: nil do
    resources :products, only: :index
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }, path: '/', path_names: { sign_in: 'log_in',
                                                                                                     sign_out: 'log_out',
                                                                                                     password: 'secret',
                                                                                                     confirmation: 'verification',
                                                                                                     unlock: 'unblock',
                                                                                                     sign_up: 'sign_up' }

  resources :users, only: %i[show edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  def sub_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :assigment_product_categories
  has_many :products, through: :assigment_product_categories
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def total_price
    quantity * product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart
  belongs_to :user
  has_many :line_items, dependent: :destroy
  after_create :send_order_mail
  after_create :send_admin_mail

  def send_order_mail
    OrderMailer.shopping_mail(self).deliver_now
  end

  def send_admin_mail
    AdminMailer.shopping_mail_admin(self).deliver_now
  end
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  has_many :assigment_product_categories
  has_many :categories, through: :assigment_product_categories
  has_many :ratings
  has_many :line_items, dependent: :destroy

  validates :title,
    presence: true,
    length: { in: 3..50 }
  validates :description,
    presence: true,
    length: { in: 16..1024 }
  validates :price,
    presence: true,
    numericality: { greater_than: 0 }

  has_one_attached :picture

  private

  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # :confirmable -> disabled devise email confirmation for heroku seeding purposes

  validates_presence_of :firstname, :lastname
  validates :email, uniqueness: true

  has_many :carts
  has_many :addresses
  has_many :orders
  has_many :ratings

  has_one_attached :avatar

  def self.admin?
    User.where(is_admin: true)
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

  private

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to store_index_url, notice: 'Invalid cart'
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @current_cart.line_items.each do |item|
      @order.line_items << item
      item.cart_id = nil
    end
    @order.save
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:name, :email, :address, :pay_method)
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user =  current_user
    user_params =  params.require(:user).permit(:firstname, :lastname, :email, :adress)
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_stripe.html.erb
<div class="container">
  <%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
    <% end %>
  </article>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="😸  Please pay to confirm your order" 
    data-amount="<%=@cart.sub_total * 100%>" 
    data-currency="eur"
    data-email=<%= current_user.email %>
    data-locale="auto"></script>
  <script>
    // Hide default stripe button, be careful there if you
    // have more than 1 button of that class
    document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
  </script>
  <button type="submit"
    class=" bg-yellow-500 hover:bg-yellow-600 font-semibold py-3 text-sm text-black uppercase w-full focus:outline-none px-">
    Checkout
  </button>
  <% end %>
</div>

app/views/carts/destroy.html.erb
<h1>Carts#destroy</h1>
<p>Find me in app/views/carts/destroy.html.erb</p>

app/views/carts/show.html.erb
<!-- cart view -->

<div class="mt-14">
  <div class="flex container shadow-md my-10  mx-auto ">
    <div class="w-3/4 px-10 py-10 yellow-background">
      <div class="flex justify-between border-b border-yellow-500 pb-8">
        <h1 class="font-semibold text-2xl">Shopping Cart</h1>
        <h2 class="font-semibold text-2xl">Meow 😸</h2>
      </div>
      <div class="cart-labels flex mt-10 mb-5">
        <h3 class="font-semibold text-gray-600 text-xs uppercase w-2/5">Product Details</h3>
        <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5">Quantity</h3>
        <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5">Price</h3>
        <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5">Total</h3>
      </div>
      <!-- LINE ITEMS LOOP -->
      <% @cart.line_items.order('id desc').each do |line_item| %>
      <div class="hover-items flex items-center -mx-8 px-6 py-5">
        <div class="flex w-2/5">
          <!-- product -->
          <div class="w-20">
            <img class="h-24" src="<%= line_item.product.img_url %>" alt="">
          </div>
          <div class="flex flex-col justify-between ml-4 flex-grow">
            <span class="font-bold text-sm"><%= line_item.product.title %></span>
            <span class="text-red-500 text-sm">Photo</span>
            <%= link_to "Remove", line_item_path(line_item), method: :delete, class:"font-semibold hover:text-red-500 text-gray-500 text-xs" %>
          </div>
        </div>

        <div class="flex justify-center w-1/5 align-middle">
          <%= link_to line_item_reduce_path(line_item), method: :post do %>
          <svg class="fill-current text-gray-600 w-3 mt-2" viewBox="0 0 448 512">
            <path
              d="M416 208H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h384c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z" />
          </svg>
          <% end %>
          <span class="font-semibold text-black mx-3 mt-1"><%= line_item.quantity %></span>
          <%= link_to line_item_add_path(line_item), method: :post do %>
          <svg class="fill-current text-gray-600 w-3 mt-2" viewBox="0 0 448 512">
            <path
              d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z" />
          </svg>
          <% end %>
        </div>
        <span
          class="text-center w-1/5 font-semibold text-sm"><%= number_to_currency(line_item.product.price, unit: '€', format: "%n%u") %></span>
        <span
          class="text-center w-1/5 font-semibold text-sm"><%= number_to_currency(line_item.total_price, unit: '€', format: "%n%u") %></span>
      </div>
      <% end %>

      <%= link_to root_path, class:"flex font-semibold text-yellow-600 text-sm mt-10" do %>
      <svg class="fill-current mr-2 text-yellow-600 w-4" viewBox="0 0 448 512">
        <path
          d="M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.09-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z" />
      </svg>
      <span>Continue Shopping </span>
      <% end %>
    </div>
    <div id="summary" class="w-1/4 px-8 py-10 bg-yellow-200">
      <h1 class="font-semibold text-2xl border-b border-yellow-500 pb-8">Order Summary</h1>
      <% @cart.line_items.each do |line_item| %>
        <div class="flex justify-between mt-10 mb-5 ">
          <span class="font-semibold text-sm uppercase"><%= line_item.quantity %> X <%= line_item.product.title %> </span>
          <span class="font-semibold text-sm"><%= number_to_currency(line_item.total_price, unit: '€', format: "%n%u") %></span>
        </div>
      <% end %>
      <div class="border-t border-yellow-400 mt-8">
        <div class="flex font-semibold justify-between py-6 text-sm uppercase">
          <span>Total cost</span>
          <span><%= number_to_currency(@cart.sub_total, unit: '€', format: "%n%u") %></span>
        </div>
        <div class="stripe">
          <% if !user_signed_in? %>
          <%= link_to 'Log In to checkout', new_user_session_path, class:"bg-yellow-500 hover:bg-yellow-600 font-semibold py-3 text-sm text-black uppercase w-full focus:outline-none px-6"%>
          <% elsif @cart.line_items.empty? %>
          <p>Your cart is empty 😸 </p>
          <% else %>
          <%= render 'stripe' %>
          <% end %>        
        </div>

      </div>
    </div>
  </div>
<div class="h-96"></div>
<div class="h-5"></div>

app/views/carts/update.html.erb
<h1>Carts#update</h1>
<p>Find me in app/views/carts/update.html.erb</p>