config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'products#index'

  resources :carts, only: %i[show destroy], path: 'my_cart'
  resource :cart, only: :show, as: :my_cart, path: 'my_cart'
  resources :products do
    resources :line_items, only: %i[create new create destroy]
  end

  resources :line_items
  post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
  post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'

  resources :orders, only: %i[index show new]
  resources :charges, only: %i[new create]

  resources :categories, only: nil do
    resources :products, only: :index
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }, path: '/', path_names: { sign_in: 'log_in',
                                                                                                     sign_out: 'log_out',
                                                                                                     password: 'secret',
                                                                                                     confirmation: 'verification',
                                                                                                     unlock: 'unblock',
                                                                                                     sign_up: 'sign_up' }

  resources :users, only: %i[show edit update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin/product.rb
class Admin::Product < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  has_many :assigment_product_categories
  has_many :categories, through: :assigment_product_categories
  has_many :ratings
  has_many :line_items, dependent: :destroy

  validates :title,
    presence: true,
    length: { in: 3..50 }
  validates :description,
    presence: true,
    length: { in: 16..1024 }
  validates :price,
    presence: true,
    numericality: { greater_than: 0 }

  has_one_attached :picture

  private

  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_admin_product, only: [:show, :edit, :update, :destroy]

  # GET /admin/products
  # GET /admin/products.json
  def index
    @admin_products = Admin::Product.all
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Admin::Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    @admin_product = Admin::Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to @admin_product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1
  # PATCH/PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @admin_product.update(admin_product_params)
        format.html { redirect_to @admin_product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_product }
      else
        format.html { render :edit }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @admin_product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Admin::Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_product_params
      params.fetch(:admin_product, {})
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
def index
  @categories = Category.all
  if params[:category_id]
    @category = Category.includes(:products)
                        .find(params[:category_id])
    @products = @category.products
  else
    @products = Product.all
  end
end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:title, :price, :img_url, :description)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_card.html.erb
<div class="md:w-1/2 xl:w-1/3 py-4 md:px-8 sm:-mt-24  md:mt-0">

  <%= link_to product_path (product.id)  do %>
  <div class="image_size_helper rounded shadow-md	">
    <%= image_tag(product.img_url)  %>
  </div>
  <% end %>
  <div
    class="flex w-full flex-col  px-8 py-4  border text-gray-900 rounded-b-md bg-triangles border-none shadow-lg mb-10 relative">
    <div class="flex w-full justify-around items-center pb-4">
      
    </div>
    <!-- SECTION: Article Preview -->

    <div class="flex  justify-items-starts justify-between py-2 px-3 -m-4">
    <div class="div">
      <span class="text-xs font-semibold inline-block py-1 px-2 rounded text-yellow-600 bg-yellow-200 uppercase last:mr-0 absolute left-0 -mt-11">
      <%= product.categories[0].name %>
      </span>
      </div>
       <%= link_to product_path (product.id)  do %>
      <h1 class="text-gray-800 font-semibold text-xl"><%= product.title %><span class="ml-6"><%= product.price%>€</span></h1>
      <% end %>
      <%= button_to line_items_path(product_id: product.id), class: 'bg-yellow-500 text-xs text-white px-2 py-1 font-semibold tracking-widest rounded uppercase hover:bg-yellow-400 absolute right-0 shadow-sm' do %>
      <%= image_pack_tag 'cart1.png', size:"30x30" %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="grid min-h-screen place-items-center mt-6">
  <div class="w-11/12 p-12 form_wrapper sm:w-8/12 md:w-1/2 lg:w-5/12 shadow-xl mb-12 rounded-lg">
  <h1 class="text-4xl	 font-bold text-center"> <span class="jumbo-header text-6xl">Meow 😸</span> 
  <br><span class="font-normal text-lg	">Editing Product</span></h1> 

  <div class="field">

    <%= form.text_field :title, class:"block w-full p-3 mt-2 text-gray-700 bg-gray-100 appearance-none focus:outline-none focus:bg-gray-200 focus:shadow-inner rounded-xl	"  %>
    <%= form.label :title, class: "block text-left text-xs font-semibold text-gray-600 uppercase mt-1 ml-2" %>
  </div>

  <div class="field">

    <%= form.text_area :description, class:"block w-full p-3 mt-2 text-gray-700 bg-gray-100 appearance-none focus:outline-none focus:bg-gray-200 focus:shadow-inner rounded-xl" %>
    <%= form.label :description, class: "block text-left text-xs font-semibold text-gray-600 uppercase mt-1 ml-2" %>
  </div>

  <div class="field">

    <%= form.text_field :price, class:"block w-full p-3 mt-2 text-gray-700 bg-gray-100 appearance-none focus:outline-none focus:bg-gray-200 focus:shadow-inner rounded-xl	" %>
    <%= form.label :price, class: "block text-left text-xs font-semibold text-gray-600 uppercase mt-1 ml-2" %>
  </div>

  <div class="actions">
    <%= form.submit "Update product", class:" cursor-pointer focus:outline-none mt-3 bg-yellow-500 hover:bg-yellow-400 py-4 px-6 block whitespace-no-wrap rounded-xl" %>
  </div>
</div>
<% end %>

app/views/products/edit.html.erb
<%= render 'form', product: @product%>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
          <!-- SECTION: Jumbotron -->
          <div class="jumbotron flex justify-between mt-12 shadow">
            <div class="content-start text-black text-4xl font-bold mt-8"></div>
          </div>
          <div class="test">

            <div class="flex flex-col items-center justify-between mx-auto p-8 md:flex-row lg:w-5/6 xl:3/4">

              <!-- SECTION: Jumbotron title + trianglify -->
              <div class="flex flex-col w-full md:w-1/2 px-0 md:px-16 justify-start items-center ">
                <div class="jumbotron-header mb-12 ">
                  <h1
                    class="text-5xl md:text-7xl lg:text-8xl font-semibold text-gray-800 lg:mr-10 jumbo-header sm:pb-8">
                    KittyPics</h1>
                </div>
                <svg class="sm:mt-12" width="120px" id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 512 512">
                  <title></title>
                  <path d="M8.57,156.87S24.12,95,55.06,140.7l29.07,55s5.84,35.78-23,44.6c0,0-50.93,5.11-61.12-47Z"
                    fill="#5b5b5f" />
                  <path
                    d="M241.8,226.63s18.07-61.16-31.83-37.56l-53,32.62s-23.2,27.84-2.84,50.13c0,0,41.27,30.24,76.56-9.48Z"
                    fill="#5b5b5f" />
                  <path
                    d="M78.37,107.58S90.33,36.4,134,52.91c0,0,17.69,14.69,11.22,70.65,0,0-11,42.59-33,46.41,0,0-30.83-3.84-34.7-26.95C77.51,143,73.67,122.25,78.37,107.58Z"
                    fill="#5b5b5f" />
                  <path
                    d="M214.41,143.55s25.85-67.34-20.15-75.37c0,0-22.69,3.69-45.6,55.16,0,0-12.2,42.22,4.87,56.78,0,0,28.5,12.32,43.57-5.58C197.1,174.53,211,158.57,214.41,143.55Z"
                    fill="#5b5b5f" />
                  <path
                    d="M44.6,98.21S48.06,82.75,57,81.16c0,0-4.19,18.13-.62,21.13a2.55,2.55,0,0,1-2.7,2.42S41.4,103.37,44.6,98.21Z"
                    fill="#5b5b5f" />
                  <path
                    d="M122.51,18.18s3.46-15.46,12.36-17c0,0-4.19,18.15-.62,21.12a2.56,2.56,0,0,1-2.7,2.42S119.29,23.35,122.51,18.18Z"
                    fill="#5b5b5f" />
                  <path
                    d="M252.13,160.63s4.87-15.06-2-21c0,0-5.63,17.78-10.2,18.54a2.54,2.54,0,0,0,1.11,3.45S252.27,166.71,252.13,160.63Z"
                    fill="#5b5b5f" />
                  <path
                    d="M208.32,40.48s4.89-15.06-2-21c0,0-5.62,17.77-10.2,18.51a2.57,2.57,0,0,0,1.11,3.47S208.48,46.57,208.32,40.48Z"
                    fill="#5b5b5f" />
                  <path
                    d="M27.91,280.54S32.8,282.3,87.46,233c0,0,35.32-33.47,50.9,13.9,0,0,23,58,27.72,64.87,0,0,11.63,32.06-21.53,45,0,0-36.59,4.23-39.21-27.07,0,0-29.26-2.81-31.23-6.82,0,0-49.84,31.64-57.71-21.35C16.39,301.51,18.66,286.19,27.91,280.54Z"
                    fill="#5b5b5f" />
                  <path
                    d="M509.05,332.42s-5.95-63.47-43.49-23l-37.1,50s-11.22,34.47,16,47.57c0,0,49.57,12.75,67.56-37.24Z"
                    fill="#5b5b5f" />
                  <path d="M268,366s-8.55-63.18,37.16-32.28L352.57,374s18.69,31.06-4.84,50c0,0-45.41,23.64-74.21-21Z"
                    fill="#5b5b5f" />
                  <path
                    d="M447.55,273.12s-1-72.14-46.71-62.5c0,0-19.71,11.87-21.83,68.12,0,0,4.35,43.76,25.61,50.91,0,0,31,.88,38.4-21.37C443,308.29,450,288.33,447.55,273.12Z"
                    fill="#5b5b5f" />
                  <path
                    d="M307.63,288s-15.31-70.5,31.37-71.42c0,0,21.88,7.09,36.7,61.44,0,0,5.63,43.57-13.44,55.36,0,0-30.07,7.87-42.24-12.13C320,321.27,308.74,303.39,307.63,288Z"
                    fill="#5b5b5f" />
                  <path
                    d="M482.36,269s-1.08-15.79-9.65-18.71c0,0,1.38,18.57-2.6,21a2.58,2.58,0,0,0,2.32,2.81S484.74,274.59,482.36,269Z"
                    fill="#5b5b5f" />
                  <path
                    d="M417.51,178.06s-1.08-15.79-9.65-18.72c0,0,1.38,18.55-2.57,21a2.58,2.58,0,0,0,2.3,2.83S419.89,183.67,417.51,178.06Z"
                    fill="#5b5b5f" />
                  <path
                    d="M267.71,299.17s-2.52-15.63,5.19-20.43c0,0,2.84,18.4,7.25,19.85a2.57,2.57,0,0,1-1.62,3.27S266.68,305.18,267.71,299.17Z"
                    fill="#5b5b5f" />
                  <path
                    d="M329.29,187.09s-2.54-15.67,5.14-20.46c0,0,2.87,18.43,7.28,19.85a2.58,2.58,0,0,1-1.62,3.26S328.23,193.05,329.29,187.09Z"
                    fill="#5b5b5f" />
                  <path
                    d="M471.16,451.76s-5.11,1-51.65-56c0,0-29.8-38.43-52.38,6,0,0-31.61,53.83-37.27,59.92,0,0-16.36,29.9,14.47,47.72,0,0,35.51,9.75,42.84-20.8,0,0,29.34,1.64,31.94-2,0,0,44.46,38.82,60.25-12.36C479.36,474.23,479.44,458.76,471.16,451.76Z"
                    fill="#5b5b5f" />
                </svg>
              </div>

              <!-- SECTION: 4 images -->
              <div class=" flex-wrap w-full hidden md:flex">
                <div class="flex p-1 w-full md:w-1/2 transform duration-200 ease-in hover:-translate-y-1">
                  <img class="rounded-md h-64 w-full object-center object-cover flex-shrink shadow"
                    src="https://alternativi.fr/uploads/articles//les-bienfaits-du-chat-sur-lhomme-e96.jpeg" alt="" />
                </div>
                <div class="flex p-1 w-full md:w-1/2  transform duration-200 ease-in hover:-translate-y-1">
                  <img class="rounded-md h-64 w-full object-center object-cover flex-shrink shadow"
                    src="https://cdn.pixabay.com/photo/2017/11/14/13/06/kitty-2948404_960_720.jpg" alt="" />
                </div>
                <div class="flex p-1 w-full md:w-1/2  transform duration-200 ease-in hover:-translate-y-1">
                  <img class="rounded-md h-64 w-full object-center object-cover flex-shrink shadow"
                    src="https://images.unsplash.com/photo-1445499348736-29b6cdfc03b9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80" />
                </div>
                <div class="flex p-1 w-full md:w-1/2  transform duration-200 ease-in hover:-translate-y-1">
                  <img class="rounded-md h-64 w-full object-center object-cover flex-shrink shadows"
                    src="https://cdn.shopify.com/s/files/1/0326/2057/6900/articles/bienfaits-du-chat-sur-les-humains2_1600x.jpg?v=1588095563"
                    alt="" />
                </div>
              </div>
            </div>
          </div>

          <!-- SECTION: filter -->
          <div class="flex flex-nowrap flex-row items-center mb-20 lg:mb-0  border-b-2 border-yellow-200 py-4 justify-around flex-auto"  >
            <div class="div mt-10">
            <%= link_to 'all', root_path, class:"bg-yellow-500 hover:bg-yellow-300 text-black mx-3 active:bg-yellow-600 font-bold uppercase text-xs px-5 py-2 rounded-full shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1"  %>           
            <% @categories.each do |category| %>                 
            <%= link_to category.name, [category, :products], method: :get, class:"mx-3 bg-yellow-500 hover:bg-yellow-400 text-black active:bg-yellow-600 font-bold uppercase text-xs px-5 py-2 rounded-full shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1" %>      
             <% end %>
            </div>
          </div>
         
          <!-- SECTION: Cards -->

            <div class="flex flex-col flex-1 items-center flex-wrap justify-between mx-auto p-8 md:flex-row lg:w-5/6 xl:3/4">
              <% @products.each do |product|%>
              <%= render "products/card", product: product %>
              <% end %>
            </div>

          </div>
          </div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<section class=" bg-transparent text-gray-900">
  <div class="flex flex-col justify-between mx-auto p-8 md:flex-row lg:w-5/6 xl:3/4">
    <div class="flex flex-col md:w-1/2 mx-2">
      <!-- SECTION: Main Image -->
      <%= image_tag(@product.img_url) %>
    </div>
    <div class="flex flex-col h-full justify-evenly px-8 items-center md:w-1/2 md:mx-2">
      <!-- SECTION: Product Title -->
      <h1 class="text-3xl text-center md:text-5xl leading-none font-semibold">
        <%= @product.title %>
      </h1>
      <!-- SECTION: Product Subtitle -->
      <h2 class="text-2xl font-light text-center mb-4">
        <%= @product.categories.first.name %>
      </h2> 
      <!-- SECTION: Product Description -->
      <p class="text-justify">
        <%= @product.description %>
      </p>      
      <div class="flex flex-col md:flex-row justify-between items-center w-full">   
        <div class="flex w-full mt-8 justify-end items-center">        
          <h2 class="text-center text-xl xl:text-2xl font-semibold w-32 border-t border-b border-l border-gray-400 rounded-l-md py-2">
            <%= @product.price %><span class="text-base">€</span>
          </h2>        
          <%= button_to "Add to cart", product_line_items_path(@product.id), class: "px-6 bg-yellow-500 border-yellow-500 text-white md:px-12 uppercase py-2 rounded-r-md text-xl border-t border-b border-r xl:text-2xl transition-colors duration-200 ease-in-out focus:outline-none hover:bg-yellow-300"
          %>
        </div>
      </div>
    </div>
  </div>
  </div>
</section>